<?php
// $Id$

/**
 * @file Creates a newsletter content type, and templating for embedding e-newsletters.
 */

/**
 * Implementation of hook_help().
 */
function newsletter_help($path, $arg) {
  if ($path == 'node/%' && user_access('administer newsletter') && is_numeric($arg[1]) && !$arg[2]) {
    $type = db_result(db_query("SELECT type FROM {node} WHERE nid = %d", $arg[1]));
    if ($type == 'newsletter') {
      return '<p>'. t('The embeddable version of this e-mail campaign is located at <strong>!path</strong>.', array('!path' => url('node/'. $arg[1] .'/newsletter', array('absolute' => TRUE)) . (variable_get('clean_url', 0) ? '' : '?q=')));
    }
  }
}
 
/**
 * Implementation of hook_menu().
 */
function newsletter_menu() {
  $items = array();

  $items['admin/settings/newsletter'] = array(
    'title' => 'Newsletter',
    'description' => 'Configure newsletter settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('newsletter_settings_form'),
    'access arguments' => array('administer newsletter'),
  );

  $items['node/%node/newsletter'] = array(
    'title callback' => 'node_page_title',
    'title arguments' => array(1),
    'page callback' => 'newsletter_page_view',
    'page arguments' => array(1),
    'access callback' => 'node_access',
    'access arguments' => array('view', 1),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Implementation of hook_perm().
 */
function newsletter_perm() {
  return array('administer newsletter');
}

/**
 * Implementation of hook_theme_registry_alter().
 */
function newsletter_theme_registry_alter(&$registry) {
  $registry['node']['theme paths'][0] = drupal_get_path('module', 'newsletter');
  array_unshift($registry['node']['theme paths'], drupal_get_path('module', 'node'));
}

/**
 * Implementation of hook_preprocess_node().
 */
function newsletter_preprocess_node(&$vars) {
  if ($vars['type'] == 'newsletter' && arg(2) == 'newsletter') {
    $node = $vars['node'];

    // Set the template file
    $vars['template_file'] = 'newsletter';

    // Load the css
    $css_file = drupal_get_path('module', 'newsletter') .'/newsletter.css';
    if (is_file($css_file)) {
      $vars['styles'] = file_get_contents($css_file);
    }

    // Load the settings variables.
    $vars['disclaimer'] = variable_get('newsletter_disclaimer', "You're receiving this email because you subscribed to our e-Newsletter.<br />\nNot interested anymore? <a href='*|UNSUB|*'>Unsubscribe Instantly</a>.  Or <a href='*|FORWARD|*'>forward</a> this email to a friend");
    $vars['footer']     = variable_get('newsletter_footer', '&copy;Copyright '. variable_get('site_name', 'Drupal'));
    $vars['closure']    = variable_get('newsletter_closure', '<a href="*|FORWARD|*">Forward</a> this email to a friend. Not interested anymore? <a href="*|UNSUB|*">Unsubscribe Instantly</a>.');

    // Load the content variables.
    $vars['header']  = $node->content['group_header']['#children'];
    $vars['content'] = $node->content['group_content']['#children'];
    $vars['sidebar'] = $node->content['group_sidebar']['#children'];
  }
}

/**
 * Menu callback to print the template to the page.
 */
function newsletter_page_view($node) {
  print node_page_view($node);
}

/**
 * Newsletter settings form
 */
function newsletter_settings_form() {
  $form = array();

  $form['newsletter_disclaimer'] = array(
    '#type' => 'textarea',
    '#title' => t('Disclaimer'),
    '#default_value' => variable_get('newsletter_disclaimer', "You're receiving this email because you subscribed to our e-Newsletter.<br />\nNot interested anymore? <a href='*|UNSUB|*'>Unsubscribe Instantly</a>.  Or <a href='*|FORWARD|*'>forward</a> this email to a friend"),
  );
  $form['newsletter_footer'] = array(
    '#type' => 'textarea',
    '#title' => t('Footer'),
    '#default_value' => variable_get('newsletter_footer', '©Copyright '. variable_get('site_name', 'Drupal')),
  );
  $form['newsletter_closure'] = array(
    '#type' => 'textarea',
    '#title' => t('Closure'),
    '#default_value' => variable_get('newsletter_closure', '<a href="*|FORWARD|*">Forward</a> this email to a friend. Not interested anymore? <a href="*|UNSUB|*">Unsubscribe Instantly</a>.'),
  );

  return system_settings_form($form);
}